### ISSUE TITLE
math.ba

### ISSUE THREAD

**Issue by ghost** [barn-lang/barn#1]
Nie umiem pull request czy czegoś tam to robię issue

```kt
fun pi() -> float  { 
  return 3.14159265359
 }
```

XDD

**Comment by SolindekDev** [comment]
> Nie umiem pull request czy czegoś tam to robię issue
> 
> ```kt
> fun pi() -> float  { 
>   return 3.14159265359
>  }
> ```
> 
> XDD

Dodam cie do organizacji to dodasz

I will add you to the organisation so you will create math.ba
