### ISSUE TITLE
dynamic print function

### ISSUE THREAD

**Issue by oliver-jt** [barn-lang/barn#3]
I took a look at the standart library of your language  and noticed that you have to use a different function to print text depending on your data type:
print
printnum
printbool
I don't know if you know what function overloading is but because your language compiles to c++ it should be possible to make a single function that works for every datatype by just using the same name for every function.

**Comment by SolindekDev** [comment]
I just added `fmt_print` function to Barn, go check out it! So basically this issue is fixed. These functions was only for time when i wasn't done with format arguments
